# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_Info',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('zone', models.CharField(max_length=100)),
                ('tenworldid', models.CharField(max_length=100)),
                ('localip', models.CharField(max_length=120)),
                ('interip', models.CharField(max_length=120)),
            ],
        ),
    ]
